export const REASSIGN_CHIPS = 'MOVE/REASSIGN_CHIPS'
export const SET_FIFTEEN_MEMO = 'MOVE/SET_FIFTEEN_MEMO'
//export const COMPLETED = 'RESULT/COMPLETED'
//export const NOT_COMPLETED = 'RESULT/NOT_COMPLETED'
